sequenceDiagram
    actor air_flow as Air Flow
    participant nb as Night Bath
    participant builder as Builder
    participant re as Risk Engine
    participant rs as Report Server
    participant gcs as Google Cloud Storage

    autonumber
    air_flow ->> nb: Trigger
    loop loop_title
        nb ->>+ builder: build
        builder -->>- nb: firebird image
        nb ->>+ re: run
        re -->>- nb: case id
        nb ->>+ re: GET /case_id
        loop pool
            re ->> re: GET Workflow Status
        end
        re ->>- nb: collation id
        nb ->>+ rs: GET Report /collation_id
        rs ->>- nb: Report
    end
    nb ->>+ nb: calculate diff
    nb ->> nb: merge
    nb ->>- gcs: save


